### ISSUE TITLE
Cannot use string offset as an array

### ISSUE THREAD

**Issue by kloewer** [tripflex/resourcify#4]
Getting an error:

Fatal error: Cannot use string offset as an array in /resourcify/includes/element-resourcify_output.php on line 8

Running PHP 5.2.12 and WordPress 3.8.1

**Comment by tripflex** [comment]
Thanks for reporting this, when/where do you get this error?  Do you have any sources specified yet or is this on a blank setup?  This is an easy fix just curious as to where you're seeing the error

**Comment by kloewer** [comment]
In posts with sources specified everything works fine, in posts without any sources specified it produces this error.

I fixed it by replacing line 8 of element-resourcify_output.php

if($sources['source_title'][0] === '') $total_sources = null;

with:

$total_sources = 0; if(isset($sources['source_title'])) $total_sources = count($sources['source_title']);

**Comment by tripflex** [comment]
Yeah I have it fixed for the next release, i'm going to try and push it today but if not I will release a patch to at least solve this problem.  New release has a lot of new features so need to test first.

Thanks again for reporting this!

**Comment by tripflex** [comment]
Thanks for this again, i've patched this version, will be releasing the new version 1.2 here shortly with template integrated
